Repository uyuni-project/sumaform, pull requests merged in 2022-07, with the labels that each got.

#1128 Add SLE Micro 5.2 support
  backend_modules/libvirt/base/main.tf
Labels: enhancement, new_image

#1130 Add SLE Micro 5.2
  modules/controller/main.tf
  modules/controller/variables.tf
  salt/controller/bashrc
Labels: cucumber_testsuite

#1132 QE: Add opensuse 15.4 image to images list for cucumber testsuite module
  modules/cucumber_testsuite/variables.tf
Labels: new_image
