Repository uyuni-project/sumaform, pull requests merged in 2022-08, with the labels that each got.

#1138 [AWS] Additional packages with scc
  salt/default/pkgs.sls
  salt/scc/clean.sls
  salt/scc/init.sls
  salt/scc/proxy.sls
  salt/scc/server.sls
Labels: enhancement

#1129 [AWS] RDS - postgres
  backend_modules/aws/README_ADVANCED.md
  backend_modules/aws/base/main.tf
  backend_modules/aws/db_host/main.tf
  backend_modules/aws/db_host/variables.tf
  backend_modules/aws/db_host/versions.tf
  backend_modules/aws/network/main.tf
  backend_modules/aws/network/variables.tf
  modules/rds/main.tf
  modules/rds/variables.tf
  modules/rds/versions.tf
Labels: enhancement

#1136 [AWS] Salt upgrade during cloud init
  backend_modules/aws/host/user_data.yaml
Labels: enhancement

#1142 QE: BV replace CentOS8 with Rocky8
  modules/controller/main.tf
  modules/controller/variables.tf
  salt/controller/bashrc
Labels: cucumber_testsuite

#1148 Create additionnal subnet and route only if RDS is deployed
  backend_modules/aws/network/main.tf
Labels: bug
